server:
  port: 8081
  forward-headers-strategy: native
  compression:
    enabled: false
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/flowable/simple/test
    username: admin
    password: 123456
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.hb0730.flowable: debug
    org.flowable: debug
    org.springframework.security: debug

management:
  endpoint:
    flowable:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
flowable:
  #定时器
  async-executor-activate: false
  idm:
    app:
      admin:
        user-id: admin
        password: test
        first-name: Test
        last-name: Administrator
        email: test-admin@example-domain.tld
  common:
    app:
      idm-admin:
        user: admin
        password: test
